name: SavagesChatGames
version: '${project.version}'
main: com.savage.chatgames.ChatGames
api-version: '1.21'
authors: [SavageDev]
description: A fun system of chat-based games to help with player engagement
commands:
  scramble:
    description: Interacts with the scramble game
    aliases: scrbl
  reloadchatgames:
    description: reloads the command
    permission: scramble.reload
